### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Phan717** [Phan717/my-first-website-working#2]
I have an issue 
<img width="1265" alt="Screen Shot 2021-01-25 at 08 55 54" src="https://user-images.githubusercontent.com/76163382/105715135-384fa000-5eeb-11eb-907d-0a149d535ade.png">

**Comment by Phan717** [comment]
Hi Chelle,
I have an issue below. How I solve this? Thanks
<img width="801" alt="Screen Shot 2021-01-25 at 09 28 46" src="https://user-images.githubusercontent.com/76163382/105719009-d34a7900-5eef-11eb-8901-94e352a76895.png">

@hellachella

**Comment by hellachella** [comment]
You have put your index file into the git folder. drag it into the root folder (called "using markbot").

**Comment by hellachella** [comment]
Please re-enter the zoom meeting.
